import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const LANGUAGE_KEY = 'fiet-iris-language'

export const languages = {
  th: { label: 'ไทย', short: 'TH', locale: 'th-TH' },
  en: { label: 'English', short: 'EN', locale: 'en-US' },
}

const translations = {
  th: {
    common: {
      all: 'ทั้งหมด',
      active: 'ปกติ',
      admin: 'ผู้ดูแลระบบ',
      advisor: 'อาจารย์',
      cancel: 'ยกเลิก',
      close: 'ปิด',
      confirm: 'ยืนยัน',
      document: 'เอกสาร',
      documents: 'เอกสาร',
      documentName: 'ชื่อเอกสาร',
      documentType: 'ประเภท',
      done: 'สำเร็จ',
      email: 'อีเมล',
      error: 'เกิดข้อผิดพลาด',
      expiringSoon: 'ใกล้หมดอายุ',
      expired: 'หมดอายุแล้ว',
      fileAttachments: 'ไฟล์แนบ',
      loading: 'กำลังโหลดข้อมูล...',
      loadingDetails: 'กำลังโหลดรายละเอียด...',
      noData: 'ยังไม่มีข้อมูล',
      noDocuments: 'ยังไม่มีเอกสาร',
      noNotifications: 'ไม่มีการแจ้งเตือน',
      noExpire: 'ไม่มีวันหมดอายุ',
      openDocuments: 'เปิดหน้าเอกสาร',
      owner: 'เจ้าของ',
      read: 'อ่านแล้ว',
      readAll: 'อ่านทั้งหมด',
      records: 'รายการ',
      save: 'บันทึก',
      saving: 'กำลังบันทึก...',
      staff: 'เจ้าหน้าที่',
      student: 'นักศึกษา',
      status: 'สถานะ',
      total: 'ทั้งหมด',
      viewAll: 'ดูทั้งหมด',
      viewDetails: 'ดูรายละเอียด',
      viewMoreDetails: 'ดูรายละเอียดเพิ่มเติม',
      user: 'ผู้ใช้',
      loggedIn: 'เข้าใช้งานระบบแล้ว',
      mainMenu: 'เมนูหลัก',
      logout: 'ออกจากระบบ',
      logoutSuccess: 'ออกจากระบบสำเร็จ',
      openMenu: 'เปิดเมนู',
      expireDate: 'หมดอายุ',
      overdueDays: 'เกินกำหนด {{days}} วัน',
      remainingDays: 'อีก {{days}} วัน',
      dash: '-',
    },
    auth: {
      signInTitle: 'เข้าสู่ระบบ FIET-IRIS',
      signInSubtitle: 'ใช้อีเมลมหาวิทยาลัย KMUTT เพื่อเข้าสู่ระบบ',
      username: 'ชื่อผู้ใช้',
      password: 'รหัสผ่าน',
      passwordPlaceholder: 'กรอกรหัสผ่าน',
      kmuttOnly: 'รองรับเฉพาะอีเมล @kmutt.ac.th',
      forgotPassword: 'ลืมรหัสผ่าน?',
      signIn: 'เข้าสู่ระบบ',
      signingIn: 'กำลังเข้าสู่ระบบ...',
      helpLine1: 'มีปัญหาในการเข้าสู่ระบบ?',
      helpLine2: 'โปรดติดต่อผู้ดูแลระบบ',
      resetTitle: 'รีเซ็ตรหัสผ่าน',
      resetDesc: 'กรอกอีเมล KMUTT ของคุณ หากพบบัญชีในระบบ ระบบจะส่งรหัสผ่านชั่วคราวให้ทางอีเมล',
      kmuttEmail: 'อีเมล KMUTT',
      sendReset: 'ส่งคำขอรีเซ็ต',
      sending: 'กำลังส่ง...',
      enterEmailPassword: 'กรุณากรอกอีเมลและรหัสผ่าน',
      enterKmuttEmail: 'กรุณากรอกอีเมล KMUTT',
      useKmuttEmail: 'กรุณาใช้อีเมล @kmutt.ac.th',
      welcome: 'ยินดีต้อนรับ {{name}}',
      signInFailed: 'เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่',
      resetSubmitted: 'ส่งคำขอรีเซ็ตรหัสผ่านแล้ว',
      resetFailed: 'ไม่สามารถส่งคำขอรีเซ็ตได้',
      changePassword: 'เปลี่ยนรหัสผ่าน',
      changePasswordDesc: 'กรุณาตั้งรหัสผ่านใหม่ก่อนเข้าใช้งานระบบ',
      mustChangePassword: 'บัญชีของคุณต้องเปลี่ยนรหัสผ่านก่อนใช้งาน',
      currentPassword: 'รหัสผ่านปัจจุบัน',
      currentPasswordPlaceholder: 'รหัสผ่านที่ได้รับจากระบบ',
      newPassword: 'รหัสผ่านใหม่',
      newPasswordPlaceholder: 'อย่างน้อย 8 ตัวอักษร',
      confirmNewPassword: 'ยืนยันรหัสผ่านใหม่',
      confirmNewPasswordPlaceholder: 'กรอกรหัสผ่านใหม่อีกครั้ง',
      saveNewPassword: 'บันทึกรหัสผ่านใหม่',
      fillAll: 'กรุณากรอกข้อมูลให้ครบถ้วน',
      minLength: 'รหัสผ่านใหม่ต้องมีอย่างน้อย 8 ตัวอักษร',
      passwordMismatch: 'รหัสผ่านใหม่และยืนยันรหัสผ่านไม่ตรงกัน',
      changeSuccess: 'เปลี่ยนรหัสผ่านสำเร็จ',
      changeFailed: 'เกิดข้อผิดพลาด กรุณาลองใหม่',
      closeResetDialog: 'ปิดหน้าต่างรีเซ็ตรหัสผ่าน',
    },
    dashboard: {
      greeting: 'สวัสดี {{name}}',
      advisorEyebrow: 'อาจารย์ที่ปรึกษา',
      advisorIntro: 'ภาพรวมใบ Certification ของนักศึกษาในที่ปรึกษา',
      staffEyebrow: 'เจ้าหน้าที่',
      staffIntro: 'ภาพรวมเอกสารของคุณ',
      allDocuments: 'เอกสารทั้งหมด',
      activeDocuments: 'ปกติ',
      expiringDocuments: 'ใกล้หมดอายุ',
      expiredDocuments: 'หมดอายุแล้ว',
      advisorDocsTitle: 'เอกสารนักศึกษาในที่ปรึกษา',
      recentDocsTitle: 'เอกสารล่าสุดของฉัน',
      uploadDocument: 'อัปโหลดเอกสาร',
      notifications: 'การแจ้งเตือน',
      tableName: 'ชื่อเอกสาร',
      tableType: 'ประเภท',
      tableExpire: 'วันหมดอายุ',
      tableStatus: 'สถานะ',
    },
    executive: {
      eyebrow: 'ผู้บริหาร',
      overviewTitle: 'ภาพรวมคณะ FIET',
      dataAsOf: 'ข้อมูล ณ วันที่ {{date}}',
      uploadTrend: 'แนวโน้มการอัปโหลดเอกสาร (6 เดือนล่าสุด)',
      noTrendData: 'ยังไม่มีข้อมูล',
      copies: 'ฉบับ',
      systemUsers: 'ผู้ใช้งานในระบบ',
      students: 'นักศึกษา',
      advisors: 'อาจารย์',
      people: 'คน',
      totalUsers: 'รวมทั้งหมด {{count}} คน',
      expiringBranches: 'สาขาที่มีเอกสารใกล้หมดอายุ',
      noExpiringBranches: 'ไม่มีเอกสารใกล้หมดอายุ',
      unspecifiedBranch: 'ไม่ระบุสาขา',
      docTypeRatio: 'สัดส่วนประเภทเอกสาร',
      certificateLabel: 'ใบประกาศ {{type}}',
      percentOfTotal: '{{percent}}% ของทั้งหมด',
    },
    notifications: {
      title: 'การแจ้งเตือน',
      unreadCount: 'ยังไม่ได้อ่าน {{count}} รายการ',
      empty: 'ไม่มีการแจ้งเตือนในขณะนี้',
      announcement: 'ประกาศ',
      shownLatest: 'แสดง {{count}} รายการล่าสุด',
      documentDetails: 'รายละเอียดเอกสาร',
      description: 'รายละเอียด',
      markReadSuccess: 'อ่านทั้งหมดแล้ว',
    },
    adminSettings: {
      title: 'ตั้งค่าระบบ',
      autoGroup: 'ตั้งค่าอัตโนมัติ',
      expiryWarningDays: 'แจ้งเตือนก่อนหมดอายุ (วัน)',
      trashRetentionDays: 'เก็บในถังขยะก่อนลบถาวร (วัน)',
      originalValue: 'ค่าเดิม {{value}}',
      noteTitle: 'หมายเหตุ',
      note1: 'ค่า expiry warning days จะมีผลทันทีหลังจากกดบันทึกการเปลี่ยนแปลง',
      note2: 'ค่า trash retention days จะมีผลเมื่อระบบเริ่มทำงานรอบถัดไป',
      note3: 'ชื่อองค์กร/คณะจะแสดงในอีเมลแจ้งเตือนอัตโนมัติ',
      loadFailed: 'โหลดการตั้งค่าไม่สำเร็จ',
      noChanges: 'ไม่มีการเปลี่ยนแปลง',
      saveSuccess: 'บันทึกการตั้งค่าเรียบร้อย',
      saveFailed: 'บันทึกไม่สำเร็จ',
      saveChanges: 'บันทึกการเปลี่ยนแปลง',
    },
    adminLogs: {
      title: 'ประวัติการลบเอกสาร',
      totalLine: 'ทั้งหมด {{count}} รายการ',
      exportCsv: 'Export CSV',
      searchPlaceholder: 'ค้นหาชื่อเอกสารหรืออีเมล...',
      allReasons: 'ทุกเหตุผล',
      autoExpired: 'หมดอายุอัตโนมัติ',
      manualAdmin: 'ลบโดย Admin',
      replacedByNew: 'แทนด้วยเอกสารใหม่',
      documentOwner: 'เจ้าของเอกสาร',
      fileName: 'ชื่อไฟล์',
      reason: 'เหตุผล',
      deletedBy: 'ลบโดย',
      deletedAt: 'วันที่ลบ',
      system: 'ระบบอัตโนมัติ',
      empty: 'ยังไม่มีประวัติการลบเอกสาร',
      loadFailed: 'โหลดข้อมูลล้มเหลว',
    },
    roles: {
      student: 'นักศึกษา',
      advisor: 'อาจารย์ที่ปรึกษา',
      staff: 'เจ้าหน้าที่',
      admin: 'ผู้ดูแลระบบ',
      executive: 'ผู้บริหาร',
      user: 'ผู้ใช้',
    },
    nav: {
      home: 'หน้าแรก',
      studentTasks: 'งานที่ต้องทำ',
      myCertificates: 'ใบประกาศของฉัน',
      studentActivity: 'ประวัติการอัปเดต',
      advisorDocuments: 'ใบประกาศ RI/IRB',
      myDocuments: 'เอกสารของฉัน',
      allCertificates: 'ใบประกาศทั้งหมด',
      users: 'จัดการผู้ใช้',
      announcements: 'จัดการประกาศ',
      documentTypes: 'ประเภทใบประกาศ',
      trash: 'ถังขยะ',
      logs: 'ประวัติระบบ',
      settings: 'ตั้งค่าระบบ',
      emailTemplates: 'จัดการ Email Template',
      executiveOverview: 'ข้อมูลภาพรวมในคณะ',
      executiveBranches: 'สรุปรายงานรายสาขาวิชา',
      executiveDocuments: 'เอกสารในคณะทั้งหมด',
    },
    topbar: {
      dashboard: 'ภาพรวมระบบ',
      documents: 'เอกสารรับรอง',
      adminUsers: 'จัดการผู้ใช้งาน',
      adminAnnouncements: 'จัดการประกาศ',
      adminDocTypes: 'ประเภทเอกสาร',
      adminTrash: 'ถังขยะ',
      adminLogs: 'ประวัติระบบ',
      adminSettings: 'ตั้งค่าระบบ',
      adminEmailTemplates: 'Email Templates',
      executiveOverview: 'ภาพรวมคณะ',
      executiveBranches: 'สรุปรายสาขา',
      executiveDocuments: 'เอกสารทั้งคณะ',
      studentTasks: 'งานที่ต้องทำ',
      studentActivity: 'ประวัติการอัปเดต',
      workspace: 'Workspace',
    },
    status: {
      active: 'ปกติ',
      expiringSoon: 'ใกล้หมดอายุ',
      expired: 'หมดอายุ',
    },
    studentDashboard: {
      eyebrow: 'หน้าแรกนักศึกษา',
      greeting: 'สวัสดี {{name}}',
      intro: 'ดูสิ่งที่ต้องจัดการก่อน แล้วค่อยเข้าไปจัดการไฟล์หรือเพิ่มเวอร์ชันในหน้าเอกสาร',
      hasProblemTitle: 'มีเอกสารที่ต้องตรวจสอบ',
      noUrgentTitle: 'วันนี้ยังไม่มีงานด่วน',
      hasProblemDesc: 'หมดอายุ {{expired}} รายการ และใกล้หมดอายุ {{expiring}} รายการ ควรเปิดเอกสารเพื่อตรวจไฟล์หรือเพิ่มเวอร์ชันล่าสุด',
      noProblemDesc: 'เอกสารของคุณยังไม่พบรายการหมดอายุหรือใกล้หมดอายุ',
      nextItem: 'รายการถัดไปที่ควรดู',
      total: 'ทั้งหมด',
      expiring: 'ใกล้หมดอายุ',
      expired: 'หมดอายุ',
      tasksTitle: 'งานที่ควรทำก่อน',
      tasksDesc: 'เฉพาะเอกสารที่หมดอายุหรือใกล้หมดอายุ',
      seeInDocuments: 'ดูในหน้าเอกสาร',
      emptyTaskTitle: 'ไม่มีงานด่วนตอนนี้',
      emptyTaskDesc: 'เมื่อมีเอกสารใกล้หมดอายุ ระบบจะแสดงรายการไว้ตรงนี้',
      versionTitle: 'เพิ่มเวอร์ชันไฟล์',
      versionDesc: 'อยู่ในรายละเอียดเอกสาร',
      stepOpen: 'เปิดหน้าเอกสาร',
      stepSelect: 'เลือกรายการที่ต้องการ',
      stepUpload: 'ใช้ส่วน "ไฟล์แนบและเวอร์ชัน"',
      notifications: 'แจ้งเตือน',
      unreadCount: 'ยังไม่ได้อ่าน {{count}} รายการ',
      noNewNotifications: 'ไม่มีการแจ้งเตือนใหม่',
    },
    studentTasks: {
      eyebrow: 'Student tasks',
      title: 'งานที่ต้องทำ',
      desc: 'รวมเอกสารที่หมดอายุหรือใกล้หมดอายุ เพื่อให้จัดการต่อได้เร็วขึ้น',
      expired: 'หมดอายุแล้ว',
      expiring: 'ใกล้หมดอายุ',
      emptyTitle: 'ยังไม่มีงานที่ต้องทำ',
      emptyDesc: 'เมื่อมีเอกสารหมดอายุหรือใกล้หมดอายุ ระบบจะแสดงรายการในหน้านี้',
      cardDesc: 'เปิดหน้าเอกสารเพื่อดูรายละเอียดไฟล์ แนบเวอร์ชันใหม่ หรือแก้ไขข้อมูลที่เกี่ยวข้อง',
    },
    studentActivity: {
      eyebrow: 'Activity',
      title: 'ประวัติการอัปเดต',
      desc: 'รวมการแจ้งเตือนและ timeline การเปลี่ยนแปลงเอกสารล่าสุด',
      emptyTitle: 'ยังไม่มีประวัติการอัปเดต',
      emptyDesc: 'เมื่อมีการแจ้งเตือนหรือการเปลี่ยนแปลงเอกสาร ระบบจะแสดงไว้ที่นี่',
      notification: 'การแจ้งเตือน',
      upload: 'อัปโหลดไฟล์',
      create: 'สร้างเอกสาร',
      update: 'อัปเดตเอกสาร',
      delete: 'ลบเอกสาร',
      approve: 'อนุมัติเอกสาร',
      restore: 'กู้คืนเอกสาร',
      timeline: 'Timeline',
    },
  },
  en: {
    common: {
      all: 'All',
      active: 'Active',
      admin: 'Administrator',
      advisor: 'Advisor',
      cancel: 'Cancel',
      close: 'Close',
      confirm: 'Confirm',
      document: 'Document',
      documents: 'Documents',
      documentName: 'Document name',
      documentType: 'Type',
      done: 'Done',
      email: 'Email',
      error: 'Something went wrong',
      expiringSoon: 'Expiring soon',
      expired: 'Expired',
      fileAttachments: 'Attachments',
      loading: 'Loading data...',
      loadingDetails: 'Loading details...',
      noData: 'No data yet',
      noDocuments: 'No documents yet',
      noNotifications: 'No notifications',
      noExpire: 'No expiration date',
      openDocuments: 'Open documents',
      owner: 'Owner',
      read: 'Read',
      readAll: 'Mark all read',
      records: 'records',
      save: 'Save',
      saving: 'Saving...',
      staff: 'Staff',
      student: 'Student',
      status: 'Status',
      total: 'Total',
      viewAll: 'View all',
      viewDetails: 'View details',
      viewMoreDetails: 'View more details',
      user: 'User',
      loggedIn: 'Signed in',
      mainMenu: 'Main menu',
      logout: 'Log out',
      logoutSuccess: 'Logged out successfully',
      openMenu: 'Open menu',
      expireDate: 'Expires',
      overdueDays: '{{days}} days overdue',
      remainingDays: '{{days}} days left',
      dash: '-',
    },
    auth: {
      signInTitle: 'Sign in to FIET-IRIS',
      signInSubtitle: 'Use your KMUTT university email to continue',
      username: 'Username',
      password: 'Password',
      passwordPlaceholder: 'Enter your password',
      kmuttOnly: 'Only @kmutt.ac.th addresses are accepted',
      forgotPassword: 'Forgot password?',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
      helpLine1: 'Having trouble signing in?',
      helpLine2: 'Please contact Administrator',
      resetTitle: 'Reset password',
      resetDesc: 'Enter your KMUTT email. If the account exists, a temporary password will be sent to you.',
      kmuttEmail: 'KMUTT Email',
      sendReset: 'Send reset',
      sending: 'Sending...',
      enterEmailPassword: 'Please enter your email and password',
      enterKmuttEmail: 'Please enter your KMUTT email',
      useKmuttEmail: 'Please use your @kmutt.ac.th email',
      welcome: 'Welcome, {{name}}',
      signInFailed: 'Sign in failed. Please try again.',
      resetSubmitted: 'Password reset request submitted',
      resetFailed: 'Unable to submit reset request',
      changePassword: 'Change password',
      changePasswordDesc: 'Please set a new password before using the system.',
      mustChangePassword: 'Your account must change password before continuing.',
      currentPassword: 'Current password',
      currentPasswordPlaceholder: 'Password received from the system',
      newPassword: 'New password',
      newPasswordPlaceholder: 'At least 8 characters',
      confirmNewPassword: 'Confirm new password',
      confirmNewPasswordPlaceholder: 'Re-enter your new password',
      saveNewPassword: 'Save new password',
      fillAll: 'Please complete all fields',
      minLength: 'New password must be at least 8 characters',
      passwordMismatch: 'New password and confirmation do not match',
      changeSuccess: 'Password changed successfully',
      changeFailed: 'Something went wrong. Please try again.',
      closeResetDialog: 'Close reset password dialog',
    },
    dashboard: {
      greeting: 'Hello {{name}}',
      advisorEyebrow: 'Advisor',
      advisorIntro: 'Certification overview for your advisees',
      staffEyebrow: 'Staff',
      staffIntro: 'Overview of your documents',
      allDocuments: 'All documents',
      activeDocuments: 'Active',
      expiringDocuments: 'Expiring soon',
      expiredDocuments: 'Expired',
      advisorDocsTitle: 'Advisee documents',
      recentDocsTitle: 'My recent documents',
      uploadDocument: 'Upload document',
      notifications: 'Notifications',
      tableName: 'Document name',
      tableType: 'Type',
      tableExpire: 'Expiration date',
      tableStatus: 'Status',
    },
    executive: {
      eyebrow: 'Executive',
      overviewTitle: 'FIET Faculty Overview',
      dataAsOf: 'Data as of {{date}}',
      uploadTrend: 'Document upload trend (last 6 months)',
      noTrendData: 'No data yet',
      copies: 'copies',
      systemUsers: 'System users',
      students: 'Students',
      advisors: 'Advisors',
      people: 'people',
      totalUsers: '{{count}} users in total',
      expiringBranches: 'Branches with expiring documents',
      noExpiringBranches: 'No expiring documents',
      unspecifiedBranch: 'Unspecified branch',
      docTypeRatio: 'Document type ratio',
      certificateLabel: '{{type}} certificates',
      percentOfTotal: '{{percent}}% of total',
    },
    notifications: {
      title: 'Notifications',
      unreadCount: '{{count}} unread',
      empty: 'No notifications right now',
      announcement: 'Announcement',
      shownLatest: 'Showing {{count}} latest items',
      documentDetails: 'Document details',
      description: 'Description',
      markReadSuccess: 'Marked all as read',
    },
    adminSettings: {
      title: 'System Settings',
      autoGroup: 'Automation settings',
      expiryWarningDays: 'Expiry warning lead time (days)',
      trashRetentionDays: 'Trash retention before permanent delete (days)',
      originalValue: 'Original value {{value}}',
      noteTitle: 'Notes',
      note1: 'expiry warning days takes effect immediately after saving changes.',
      note2: 'trash retention days takes effect on the next scheduled system run.',
      note3: 'Organization/faculty name appears in automatic notification emails.',
      loadFailed: 'Unable to load settings',
      noChanges: 'No changes',
      saveSuccess: 'Settings saved',
      saveFailed: 'Unable to save settings',
      saveChanges: 'Save changes',
    },
    adminLogs: {
      title: 'Document Deletion Logs',
      totalLine: '{{count}} records',
      exportCsv: 'Export CSV',
      searchPlaceholder: 'Search document name or email...',
      allReasons: 'All reasons',
      autoExpired: 'Auto expired',
      manualAdmin: 'Deleted by admin',
      replacedByNew: 'Replaced by new document',
      documentOwner: 'Document owner',
      fileName: 'File name',
      reason: 'Reason',
      deletedBy: 'Deleted by',
      deletedAt: 'Deleted at',
      system: 'System',
      empty: 'No deletion logs yet',
      loadFailed: 'Unable to load data',
    },
    roles: {
      student: 'Student',
      advisor: 'Advisor',
      staff: 'Staff',
      admin: 'Administrator',
      executive: 'Executive',
      user: 'User',
    },
    nav: {
      home: 'Home',
      studentTasks: 'Tasks',
      myCertificates: 'My Certificates',
      studentActivity: 'Update History',
      advisorDocuments: 'RI/IRB Certificates',
      myDocuments: 'My Documents',
      allCertificates: 'All Certificates',
      users: 'User Management',
      announcements: 'Announcements',
      documentTypes: 'Certificate Types',
      trash: 'Trash',
      logs: 'System Logs',
      settings: 'Settings',
      emailTemplates: 'Email Templates',
      executiveOverview: 'Faculty Overview',
      executiveBranches: 'Branch Reports',
      executiveDocuments: 'Faculty Documents',
    },
    topbar: {
      dashboard: 'Dashboard',
      documents: 'Certificates',
      adminUsers: 'User Management',
      adminAnnouncements: 'Announcements',
      adminDocTypes: 'Document Types',
      adminTrash: 'Trash',
      adminLogs: 'System Logs',
      adminSettings: 'System Settings',
      adminEmailTemplates: 'Email Templates',
      executiveOverview: 'Faculty Overview',
      executiveBranches: 'Branch Summary',
      executiveDocuments: 'Faculty Documents',
      studentTasks: 'Tasks',
      studentActivity: 'Update History',
      workspace: 'Workspace',
    },
    status: {
      active: 'Active',
      expiringSoon: 'Expiring soon',
      expired: 'Expired',
    },
    studentDashboard: {
      eyebrow: 'Student home',
      greeting: 'Hello {{name}}',
      intro: 'Review what needs attention first, then manage files or add new versions from the documents page.',
      hasProblemTitle: 'Documents need attention',
      noUrgentTitle: 'No urgent tasks today',
      hasProblemDesc: '{{expired}} expired and {{expiring}} expiring documents need review. Open the document page to check files or add the latest version.',
      noProblemDesc: 'Your documents do not have expired or expiring items right now.',
      nextItem: 'Next item to review',
      total: 'Total',
      expiring: 'Expiring',
      expired: 'Expired',
      tasksTitle: 'Priority tasks',
      tasksDesc: 'Only expired or expiring documents are shown here',
      seeInDocuments: 'View in documents',
      emptyTaskTitle: 'No urgent tasks',
      emptyTaskDesc: 'Expiring documents will appear here when action is needed.',
      versionTitle: 'Add file versions',
      versionDesc: 'Available in document details',
      stepOpen: 'Open the documents page',
      stepSelect: 'Select the document you need',
      stepUpload: 'Use "Attachments and versions"',
      notifications: 'Notifications',
      unreadCount: '{{count}} unread',
      noNewNotifications: 'No new notifications',
    },
    studentTasks: {
      eyebrow: 'Student tasks',
      title: 'Tasks',
      desc: 'Expired and expiring documents are grouped here so you can act faster.',
      expired: 'Expired',
      expiring: 'Expiring soon',
      emptyTitle: 'No tasks yet',
      emptyDesc: 'Expired or expiring documents will appear on this page.',
      cardDesc: 'Open the document page to review files, attach a new version, or update related details.',
    },
    studentActivity: {
      eyebrow: 'Activity',
      title: 'Update History',
      desc: 'Recent notifications and document timeline events are shown here.',
      emptyTitle: 'No activity yet',
      emptyDesc: 'Notifications and document updates will appear here when they happen.',
      notification: 'Notification',
      upload: 'File upload',
      create: 'Document created',
      update: 'Document updated',
      delete: 'Document deleted',
      approve: 'Document approved',
      restore: 'Document restored',
      timeline: 'Timeline',
    },
  },
}

const LanguageContext = createContext(null)

function resolveValue(source, path) {
  return path.split('.').reduce((value, segment) => value?.[segment], source)
}

function interpolate(value, params = {}) {
  if (typeof value !== 'string') return value
  return Object.entries(params).reduce(
    (text, [key, paramValue]) => text.replaceAll(`{{${key}}}`, paramValue ?? ''),
    value
  )
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    if (typeof window === 'undefined') return 'th'
    return localStorage.getItem(LANGUAGE_KEY) || 'th'
  })

  const setLanguage = (nextLanguage) => {
    const normalized = languages[nextLanguage] ? nextLanguage : 'th'
    setLanguageState(normalized)
    localStorage.setItem(LANGUAGE_KEY, normalized)
  }

  const toggleLanguage = () => setLanguage(language === 'th' ? 'en' : 'th')

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  const value = useMemo(() => {
    const locale = languages[language]?.locale || 'th-TH'
    const t = (key, params) => {
      const translated = resolveValue(translations[language], key) ?? resolveValue(translations.th, key) ?? key
      return interpolate(translated, params)
    }

    return {
      language,
      locale,
      languages,
      setLanguage,
      toggleLanguage,
      t,
    }
  }, [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
